title: FoundPhys
description: Personal Educational Physics Project
baseurl: "/FoundPhys"
url: "https://begimaitoigonbaevna-cloud.github.io"

markdown: kramdown
kramdown:
  math_engine: mathjax

theme: null
