title: FoundPhys
description: Personal Educational Physics Project

header_pages:
  - index.md
  - en/harmonic.md
  - ru/harmonic.md
  - en/electrodynamics.md
  - ru/electrodynamics.md
  - en/mechanics.md
  - ru/mechanics.md
  - en/thermodynamics.md
  - ru/thermodynamics.md
