title: FoundPhys
description: Personal Educational Physics Project
theme: minima
baseurl: "/FoundPhys"
url: "https://begimaitoigonbaevna-cloud.github.io"

markdown: kramdown
kramdown:
  math_engine: mathjax

theme: null

header_pages:
  - index.md
  - en/harmonic.md
  - ru/harmonic.md
  - index.md
  - en/harmonic.md
  - ru/harmonic.md
  - en/electrodynamics.md
  - ru/electrodynamics.md
  - en/mechanics.md
  - ru/mechanics.md
  - en/thermodynamics.md
  - ru/thermodynamics.md
